### Get all planets

GET http://localhost:8080/api/planets

### Get all stars

GET http://localhost:8080/api/stars

### Get planets from star
GET http://localhost:8080/api/stars/f5875513-bf7b-4ae1-b8a5-5b70a1b90e76/planets

### Get planets from star no exist
GET http://localhost:8080/api/stars/f5875513-bf7b-4ae1-b8a5-5b70a1b90e06/planets

### Get planets from star empty
GET http://localhost:8080/api/stars/f5875513-bf8b-4ae1-b8a5-5b70a1b90e78/planets

### Puts planet
PUT http://localhost:8080/api/planets/3c6f1eb1-8069-44ab-988f-d7fed2b65d87
Content-Type: application/json
Authorization: Basic a2V2aW46dXNlcnVzZXI=

{
  "name": "Mars",
  "population": 6000,
  "star": "f5875513-bf7b-4ae1-b8a5-5b70a1b90e76"
}

### Get created planet
GET http://localhost:8080/api/planets/3c6f1eb1-8069-44ab-988f-d7fed2b65d87

### Update planet
PATCH http://localhost:8080/api/planets/3c6f1eb1-8069-44ab-988f-d7fed2b65d87
Content-Type: application/json
Authorization: Basic a2V2aW46dXNlcnVzZXI=

{
  "name": "ZZZZ",
  "population": 4,
  "star": "f5875513-bf7b-4ae1-b8a5-5b70a1b90e76"
}

### Get updated planet
GET http://localhost:8080/api/planets/3c6f1eb1-8069-44ab-988f-d7fed2b65d87

### Remove updated planet
DELETE http://localhost:8080/api/planets/3c6f1eb1-8069-44ab-988f-d7fed2b65d87

### Get stars
GET http://localhost:8080/api/stars

### Get Star
GET http://localhost:8080/api/stars/f5875513-bf7b-4ae1-b8a5-5b70a1b90e76

### Create Star
PUT http://localhost:8080/api/stars/3c6f1eb1-8069-44ab-988f-d7fed2b65d49
Content-Type: application/json
Authorization: Basic a2V2aW46dXNlcnVzZXI=

{
  "name": "Sol",
  "age": 5
}

### Get created star
GET http://localhost:8080/api/stars/3c6f1eb1-8069-44ab-988f-d7fed2b65d49

### Update-star
PATCH http://localhost:8080/api/stars/f5875513-bf7b-4ae1-b8a5-5b70a1b90e76
Content-Type: application/json
Authorization: Basic a2V2aW46dXNlcnVzZXI=

{
  "name": "AAAA",
  "age": 1
}

### Get updated star
GET http://localhost:8080/api/stars/f5875513-bf7b-4ae1-b8a5-5b70a1b90e76

### Get planets from star to remove
GET http://localhost:8080/api/stars/f5875513-bf7b-4ae1-b8a5-5b70a1b90e76/planets

### Remove star with planets
DELETE http://localhost:8080/api/stars/f5875513-bf7b-4ae1-b8a5-5b70a1b90e76

### Get stars
GET http://localhost:8080/api/stars

### Get planets
GET http://localhost:8080/api/planets


